from __future__ import annotations

from okx_nft_bot.sniper.offer_blaster_accounting import install_offer_blaster_accounting
from okx_nft_bot.sniper.opensea_mirror_safety import install_opensea_mirror_safety
from okx_nft_bot.sniper.opensea_submit_route_safety import install_opensea_submit_route_safety
from okx_nft_bot.sniper.opensea_effect_boundary_safety import install_opensea_effect_boundary_safety
from okx_nft_bot.sniper.opensea_conduit_allowance_safety import install_opensea_conduit_allowance_safety
from okx_nft_bot.sniper.opensea_single_attempt_submit_safety import install_opensea_single_attempt_submit_safety
from okx_nft_bot.sniper.opensea_receipt_reconciliation import install_opensea_receipt_reconciliation
from okx_nft_bot.sniper.token_zero_scope_safety import install_token_zero_scope_safety
from okx_nft_bot.sniper.sell_token_zero_safety import install_sell_token_zero_safety
from okx_nft_bot.sniper.sell_cancel_confirmation_safety import install_sell_cancel_confirmation_safety
from okx_nft_bot.sniper.offer_blaster import OfferBlaster
from okx_nft_bot.sniper.counter_bidder import CounterBidder
from okx_nft_bot.counterbid.okx_api import OKXAPIClient
from okx_nft_bot.clients.opensea import OpenSeaClient

install_offer_blaster_accounting(OfferBlaster, OKXAPIClient)
install_opensea_submit_route_safety(OpenSeaClient)
install_opensea_effect_boundary_safety(OpenSeaClient)
install_opensea_conduit_allowance_safety(OpenSeaClient)
install_opensea_single_attempt_submit_safety(OpenSeaClient)
install_token_zero_scope_safety(CounterBidder)
install_sell_token_zero_safety(CounterBidder)
install_sell_cancel_confirmation_safety(CounterBidder)
install_opensea_mirror_safety(CounterBidder, OpenSeaClient)
install_opensea_receipt_reconciliation(CounterBidder, OpenSeaClient)
